server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: http://gitlab.mwbyd.cn:10080/personalachievements/central-config-repo-test.git
          username: su.songyan@puscene.com
          password: Ssy123!@#
          clone-on-start: true # 应用启动就拉取配置，默认是第一次使用配置的时候拉取
        health: # 通过url  xx/health/microservice-foo-dev/master 查看配置健康状况
          repositories:
            microservice-foo:
              label: config-label-v2.0
              name: microservice-foo
              profiles: dev
      bus:
        trace:
          enabled: true # 开启 bus 跟踪
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

management:
  security:
    enabled: false